title: "TCDS-FARO"
description: "Synchronic Chromodynamics Theory — Σ–χ formalism, Synchronon σ, ΣFET, CSL-H, LBCU."
author:
  name: "Genaro Carrasco Ozuna"
  url: "https://geozunac3536-jpg.github.io/TCDS-FARO/"
  email: "genarocarrascoozuna@proton.me"
  affiliation: "Proyecto TCDS — Canon Paradigmático"
