title: "LBCU — Ley de Balance Coherencial Universal"
description: "Paradigm of coherent balance derived from TCDS — universal falsifiable framework."
author: "Genaro Carrasco Ozuna"
url: "https://geozunac3536-jpg.github.io/LBCU"
theme: jekyll-theme-cayman
lang: "es-MX"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
